import React, { useState, useEffect } from "react";
import { Box, Typography, Card, CardContent, CircularProgress } from "@mui/material";
import { Brain, TrendingUp, AlertTriangle, Briefcase, Zap } from "lucide-react";
import { motion } from "framer-motion";
import { useAuth } from "../../context/AuthContext";
import api from "../../api/api";

const iconMap = {
  AlertTriangle: <AlertTriangle color="#f59e0b" size={32} />,
  Briefcase: <Briefcase color="#10b981" size={32} />,
  TrendingUp: <TrendingUp color="#3b82f6" size={32} />,
  Brain: <Brain color="#8b5cf6" size={32} />,
  Zap: <Zap color="#f59e0b" size={32} />
};

export default function AISuggestionsPage() {
  const { user } = useAuth();
  const [suggestions, setSuggestions] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchSuggestions = async () => {
      setLoading(true);
      try {
        let contextData = "";
        
        if (user?.role === "ROLE_CLIENT") {
          const res = await api.get("/projects/mine");
          contextData = JSON.stringify(res.data);
        } else {
          const res = await api.get("/freelancers/me");
          contextData = JSON.stringify(res.data);
        }

        let prompt = "";
        if (user?.role === "ROLE_CLIENT") {
          prompt = `Analyze my active projects in the dashboard context. Output EXACTLY 3 insights for me as a CLIENT (e.g., project health, budget optimization, freelancer hiring suggestions). Output ONLY a valid JSON array. No markdown, no intro text. Example format: [{"title": "Budget Alert", "desc": "Your project is under budget.", "iconName": "AlertTriangle"}] (iconName must be Brain, AlertTriangle, Briefcase, TrendingUp, or Zap).`;
        } else {
          prompt = `Analyze my profile data in the dashboard context. Output EXACTLY 3 insights for me as a FREELANCER (e.g., skill gaps, rate suggestions, profile tips). Output ONLY a valid JSON array. No markdown, no intro text. Example format: [{"title": "Skill Spotlight", "desc": "You are great at Python.", "iconName": "Brain"}] (iconName must be Brain, AlertTriangle, Briefcase, TrendingUp, or Zap).`;
        }

        const chatRes = await api.post("/chat", {
          message: prompt,
          role: user?.role === "ROLE_CLIENT" ? "client" : "freelancer",
          user_name: user?.fullName || "User",
          dashboard_context: contextData.substring(0, 800)
        });

        const textResp = typeof chatRes.data === "string" ? chatRes.data : chatRes.data?.response;
        
        const match = textResp.match(/\[[\s\S]*\]/);
        if (match) {
          const parsed = JSON.parse(match[0]);
          setSuggestions(parsed);
        } else {
          throw new Error("No JSON array found in response");
        }
      } catch (err) {
        console.error("Failed to load AI suggestions:", err);
        // Fallback
        setSuggestions(user?.role === "ROLE_CLIENT" ? [
          { title: "Project Scope Alert", desc: "Consider adding React and Node.js to your next project for better matches.", iconName: "AlertTriangle" },
          { title: "Freelancer Match", desc: "We found 3 new teams that match your recent open project.", iconName: "Briefcase" }
        ] : [
          { title: "Skill Gap Detected", desc: "Most AI projects require PyTorch. Adding this could increase your match rate by 42%.", iconName: "Brain" },
          { title: "Profile Optimization", desc: "Your response time is excellent! Highlight this in your bio to attract more clients.", iconName: "Zap" }
        ]);
      } finally {
        setLoading(false);
      }
    };

    if (user) {
      fetchSuggestions();
    }
  }, [user]);

  return (
    <Box sx={{ maxWidth: 1200, margin: "0 auto" }}>
      <Box sx={{ display: "flex", alignItems: "center", gap: 2, mb: 4 }}>
        <Brain size={32} color="#997E67" />
        <Typography variant="h4" sx={{ fontWeight: "bold", color: "#FFDBBB" }}>
          {user?.role === "ROLE_CLIENT" ? "AI Insights" : "AI Suggestions"}
        </Typography>
      </Box>
      <Typography variant="body1" sx={{ color: "#d1d5db", mb: 4 }}>
        Personalized, real-time recommendations generated by the ProLance AI Engine based on your specific profile and live market trends.
      </Typography>

      {loading ? (
        <Box sx={{ display: "flex", justifyContent: "center", mt: 8 }}>
          <CircularProgress sx={{ color: "#FFDBBB" }} />
        </Box>
      ) : (
        <Box sx={{ display: "flex", flexDirection: "column", gap: 3 }}>
          {suggestions.map((s, i) => (
            <motion.div key={i} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.1 }}>
              <Card sx={{ bgcolor: "rgba(255,219,187,0.02)", border: "1px solid rgba(153,126,103,0.2)", borderRadius: 3 }}>
                <CardContent sx={{ display: "flex", alignItems: "flex-start", gap: 3, p: 3 }}>
                  <Box sx={{ p: 2, bgcolor: "rgba(255,255,255,0.05)", borderRadius: 2 }}>
                    {iconMap[s.iconName] || <Brain color="#997E67" size={32} />}
                  </Box>
                  <Box>
                    <Typography variant="h6" sx={{ color: "#FFDBBB", mb: 1, fontWeight: "bold" }}>{s.title}</Typography>
                    <Typography variant="body2" sx={{ color: "#9ca3af", lineHeight: 1.6 }}>{s.desc}</Typography>
                  </Box>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </Box>
      )}
    </Box>
  );
}

